### ISSUE TITLE
ModuleNotFoundError: No module named 'rastervision'

### ISSUE THREAD

**Issue by winsento** [azavea/raster-vision-qgis#5]
Install from `Plugins > Manage and Install plugins ...`
```
Couldn't load plugin 'rastervision_qgis' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'rastervision' 
Traceback (most recent call last):
  File "/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/zhopa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/__init__.py", line 30, in classFactory
    from .raster_vision import RasterVisionPlugin
  File "/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/zhopa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/raster_vision.py", line 27, in 
    from .registry import Registry
  File "/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/zhopa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rastervision_qgis/registry.py", line 1, in 
    import rastervision as rv
  File "/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'rastervision'


Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.6.1-Noosa Noosa, exported 

Python Path:
/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python
/Users/zhopa/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/zhopa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins
/usr/local/opt/osgeo-gdal-python/lib/python3.7/site-packages
/usr/local/opt/osgeo-qgis/QGIS.app/Contents/Resources/python
/usr/local/opt/osgeo-qgis/lib/python3.7/site-packages
/usr/local/opt/lib/python3.7/site-packages
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geos
/usr/local/Cellar/osgeo-matplotlib/3.0.3_1/libexec/lib/python3.7/site-packages
/usr/local/Cellar/numpy/1.16.2/libexec/nose/lib/python3.7/site-packages
/usr/local/Cellar/protobuf/3.7.1/libexec/lib/python3.7/site-packages
/Users/zhopa/Library/Application Support/QGIS/QGIS3/profiles/default/python
/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/IPython/extensions
/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/IPython/extensions
/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/IPython/extensions
```

**Comment by winsento** [comment]
Need to install `rastervision ` before. 
`pip install rastervision `
